apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: oadp-operator
  namespace: openshift-adp
spec:
  channel: beta
  installPlanApproval: Automatic
  name: oadp-operator
  source: community-operators
  sourceNamespace: openshift-marketplace